export const SET_START_COUNTER = 'SET_START_COUNTER'
export const START_SET_START_COUNTER = 'START_SET_START_COUNTER'

export const SET_CURRENT_COUNTER = 'SET_CURRENT_COUNTER'

export const SET_END_COUNTER = 'SET_END_COUNTER'
export const START_SET_END_COUNTER = 'START_SET_END_COUNTER'